### ISSUE TITLE
Doesn't work on Bodacious Berries

### ISSUE THREAD

**Issue by eristhea** [P03W/Machete#2]
In my mod [Bodacious Berries](https://github.com/ix0rai/bodaciousberries) I have [this disaster of a blockstate](https://github.com/ix0rai/bodaciousberries/blob/master/src/main/resources/assets/bodaciousberries/blockstates/grapevine.json) which seems to explode when compiled with Machete 1.0.6.  
I'm not sure what causes this, but when my mod is compiled with Machete grapevines have no textures or models, which I can pretty safely say is because of Machete encountering an error when dealing with that blockstate file. Please fix this so I can use Machete in my project and recommend it to friends :)
it's a really nice tool!

**Comment by SilverAndro** [comment]
Could you check with 1.0.8? 1.0.7 (I'm pretty sure) changed the JSON optimization code, and will fallback to default if it still fails somehow (although will print an error)

**Comment by eristhea** [comment]
1.0.8 works, thank you!

**Comment by SilverAndro** [comment]
Awesome, glad to hear!
