### ISSUE TITLE
Cannot find Oxipng

### ISSUE THREAD

**Issue by isXander** [P03W/Machete#3]
When building, I get this error.
```log
java.io.IOException: Cannot run program "/home/xander/Code/W-OVERFLOW/Debugify/forge/build/machete-build/oxipng": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at io.github.p03w.machete.util.InvokeProcessKt.invokeProcess(invokeProcess.kt:11)
	at io.github.p03w.machete.core.OxipngManager.optimize(OxipngManager.kt:106)
	at io.github.p03w.machete.core.JarOptimizer.optimizePNG(JarOptimizer.kt:57)
	at io.github.p03w.machete.core.JarOptimizer.optimize(JarOptimizer.kt:141)
	at io.github.p03w.machete.tasks.OptimizeJarsTask.optimizeJars(OptimizeJarsTask.kt:29)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
```
I believe this is because I have a multiproject build and oxipng is only being downloaded for the root project.

Maybe consider this:
1. Use system-provided oxipng if present
2. Always run oxipng from rootProject

**Comment by SilverAndro** [comment]
Would you be willing to provide the full `gradle build -i` log?

If its applying to subdirectories it should apply, and therefore unpack it, and if it fails to unpack, it should warn instead of doing that

Although yeah using the system provided oxipng is a good idea, I'll look into that

**Comment by isXander** [comment]
> Would you be willing to provide the full `gradle build -i` log?
> 
> If its applying to subdirectories it should apply, and therefore unpack it, and if it fails to unpack, it should warn instead of doing that
> 
> Although yeah using the system provided oxipng is a good idea, I'll look into that

https://hst.sh/arimeyiruf.http

**Comment by SilverAndro** [comment]
Alright thanks much, I'll check this out later today

**Comment by SilverAndro** [comment]
Hm, can you show what files are under forge/build/machete-build after a failed build? I suspect I know whats going on but need to confirm

**Comment by isXander** [comment]
> Hm, can you show what files are under forge/build/machete-build after a failed build? I suspect I know whats going on but need to confirm

`jar`, `remapJar`, and `shadowJar` are the only things present.

**Comment by SilverAndro** [comment]
Well thats concerning, thanks

**Comment by SilverAndro** [comment]
Can you check if 1.1.1 fixes this issue?

**Comment by isXander** [comment]
It does not.

**Comment by SilverAndro** [comment]
Alright well that's not great, new log if you've got the time? Added more logging to the plugin

**Comment by isXander** [comment]
https://hst.sh/ohapawobuq.http

**Comment by SilverAndro** [comment]
Well I'm completely lost 🤔 

So, the "should be here" log points to the same location, and it passes the "does file exist" check, but then only explodes when it goes to run, saying it doesn't exist? Very bizarre.
Ill try and look into this (maybe implement system install first?), but figuring this out may take a while, can you think of anything on your system/dev env that might cause issues with copying files or unpacking binary blobs?

**Comment by isXander** [comment]
No but maybe it did exist. And something overwrote it.

**Comment by isXander** [comment]
Oh, I found out what is happening.

My build task is actually clean build. Not just build. Machete seems to export the oxipng binary before it cleans.

**Comment by SilverAndro** [comment]
Ahhhhh that would explain it, thanks a ton!

Ill implement a guard against that right now, should hopefully get it using the installed version soon as well

**Comment by SilverAndro** [comment]
Apologies for the delay, was having significant issues testing due to gradle caches. Can you check if 1.1.2 works? (It should use your native install as well)

**Comment by isXander** [comment]
All good! Thanks!

**Comment by SilverAndro** [comment]
wooo, glad I could help
